---
language: rust
sudo: false
rust:
  - nightly
  - stable
env:
  - DENYWARNINGS=
  - DENYWARNINGS=1
matrix:
  include:
    - rust: nightly
      env: BENCHMARK=1
  allow_failures:
    - rust: stable

